@startuml change_temparature

title Change temprature

participant RemoteCtrl
participant RFComm
participant SystemCtrl
participant Motor
participant ShareOBJ
participant Display

RemoteCtrl->>RFComm:SetTemperature(new_temp=param)
activate RFComm
hnote over SystemCtrl: Idle

RFComm->>SystemCtrl:SetTemperature(new_temp=param)
deactivate RFComm
activate SystemCtrl
SystemCtrl->>Motor:SetTemperature(new_temp=param)
deactivate SystemCtrl
activate Motor

hnote over SystemCtrl: Working
Motor->>SystemCtrl:SetTemperatureResult(result=OK)
deactivate Motor
activate SystemCtrl
alt succeed
SystemCtrl->>A:Test1
activate A

alt OK
loop 100times  /'add by shiweiz begin'/
SystemCtrl->>Motor:Test2
activate Motor
deactivate Motor
end

else NG
loop 100times
alt OK
SystemCtrl->>Motor:Test3
activate Motor
deactivate Motor
else
SystemCtrl->>Motor:Test4
activate Motor
deactivate Motor
end
end
end /'add by shiweiz end'/


loop 100times
A->B:Test2
activate B
B-->A:OK
deactivate B
end
deactivate A
else failed
SystemCtrl->>A:Test11
activate A
A->B:Test22
activate B
B-->A:OK
deactivate B
deactivate A
end
SystemCtrl->>Display:ShowTemperature(new_temp=param)
deactivate SystemCtrl
activate Display

Display->>SystemCtrl:ShowTemperatureResult(result=OK)
deactivate Display
activate SystemCtrl
SystemCtrl->ShareOBJ:SetTemperature(new_temp=param)
activate ShareOBJ
ShareOBJ-->SystemCtrl:OK
deactivate ShareOBJ

SystemCtrl->>RFComm:SetTemperatureResult(result=OK)
deactivate SystemCtrl
hnote over SystemCtrl: Idle 
activate RFComm
RFComm->>RemoteCtrl : SetTemperatureResult(OK)
deactivate RFComm

@enduml

