
@startuml  compontent

/' UserReq_Id: xxx1;xxx2
   Arch_Id: xxx1
'/
component RemoteCtrl    /' STM     RC_uninitialized '/
component RFComm        /' SERVICE none '/
component SystemCtrl    /' STM     SC_uninitialized '/
component ShareOBJ      /' LIB     none '/
component Motor         /' STM     M_uninitialized '/
component Display       /' SERVICE none '/

@enduml