@startuml power_on
title Power on

hide footbox


RemoteCtrl->>RFComm : Power on
activate RFComm
hnote over SystemCtrl: SC_uninitialized
RFComm->>SystemCtrl:PowerOn()
deactivate RFComm
activate SystemCtrl
SystemCtrl->SystemCtrl:Initilize
activate SystemCtrl
deactivate SystemCtrl
SystemCtrl->ShareOBJ:ReadLastTemeprature
activate ShareOBJ
ShareOBJ-->SystemCtrl:lv_last_temprature:int32
deactivate ShareOBJ
SystemCtrl->ShareOBJ:ReadLastMode
activate ShareOBJ
ShareOBJ-->SystemCtrl:lv_last_mode
deactivate ShareOBJ
SystemCtrl->>Motor:PowerOn(last_temperature=lv_last_temprature, last_mode=lv_last_mode)
deactivate SystemCtrl
activate Motor
Motor->>SystemCtrl: PowerOnResult(result=OK)
deactivate Motor
activate SystemCtrl
SystemCtrl->>Display:ShowTemperature(last_temprature=lv_last_temprature)
deactivate SystemCtrl
activate Display
Display->>SystemCtrl:ShowTemperatureResult(result=OK)
deactivate Display
activate SystemCtrl

SystemCtrl->>RFComm:PowerOn(result=OK)
deactivate SystemCtrl
hnote over SystemCtrl: Idle
activate RFComm
RFComm->>RemoteCtrl:PowerOn(result=OK)
deactivate RFComm

@enduml