@startuml power_off

title Power Off

RemoteCtrl->>RFComm: PowerOff
activate RFComm
hnote over SystemCtrl: Idle

RFComm->>SystemCtrl: PowerOff
deactivate RFComm
activate SystemCtrl

SystemCtrl->>Motor: PowerOff
deactivate SystemCtrl
activate Motor

Motor->>SystemCtrl:PowerOffResult(result=OK)
deactivate Motor

activate SystemCtrl
SystemCtrl->>Display:TurnOffDisplay
deactivate SystemCtrl

activate Display
Display->>SystemCtrl:TurnOffDisplayResult(result=OK)
deactivate Display
activate SystemCtrl
SystemCtrl->>RFComm:PowerOffResult(result=OK)
deactivate SystemCtrl
activate RFComm
RFComm->>RemoteCtrl:PowerOffResult(result=OK)
deactivate RFComm

@enduml
