

@startuml SystemCtrl's state chart

[*] --> Unitialized

Idle --> Working : SetTemperature
Working --> Idle : ShowTemperatureResult
Idle --> Unitialized : TurnOffDisplayResult
Unitialized --> Idle : ShowTemperatureResult

@enduml


       